### ISSUE TITLE
Migrations not running

### ISSUE THREAD

**Issue by edsu** [DocNow/docnow-ansible#54]
I noticed that the db migrations are not running as part of the playbook. Here is what I see when I try to run them manually. It looks like they are trying to connect to the wrong db host for some reason:

```
pulsys@demo:/var/local/docnow_app/docnow$ node_modules/.bin/knex migrate:up
error: no pg_hba.conf entry for host "127.0.0.1", user "pulsys", database "pulsys", SSL off
    at Parser.parseErrorMessage (/var/local/docnow_app/docnow/node_modules/pg-protocol/dist/parser.js:241:15)
    at Parser.handlePacket (/var/local/docnow_app/docnow/node_modules/pg-protocol/dist/parser.js:89:29)
    at Parser.parse (/var/local/docnow_app/docnow/node_modules/pg-protocol/dist/parser.js:41:38)
    at Socket.<anonymous> (/var/local/docnow_app/docnow/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by kayiwa** [comment]
hey @edsu those migrations should run as the docnow user 

https://github.com/DocNow/docnow-ansible/blob/88108f60489bdc1d9146441846db1e5322ca3c4c/roles/docnow_role/tasks/main.yml#L91

**Comment by kayiwa** [comment]
your example is running as the `pulsys` user. 

what does `sudo su - docnow node_modules/.bin/knex migrate:up` 

give you?

**Comment by edsu** [comment]
Thanks @kayiwa. I seem to be seeing the same error when running as `docnow`.

**Comment by edsu** [comment]
Although they have to be running at some point because the schema wouldn't be there otherwise :-) I'll investigate further.

**Comment by kayiwa** [comment]
I have added a `.pgpass` on the docnow user that I will add a PR to the ansible role which will also prevent the installation of postgresql when run here.

**Comment by kayiwa** [comment]
> Although they have to be running at some point because the schema wouldn't be there otherwise :-) I'll investigate further.

please try to re-run now. I have run `psql` and it automagically connects to the right DB. I will make sure this sticks all the time.

**Comment by edsu** [comment]
I noticed that the ordering of the migrations was off which might have caused them to run out of sequence which would not work. I ran the playbook again, but now I see:

```
TASK [postgresql | create postgresql database] **********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
failed: [docnow-demo1] (item=docnow_dev) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "docnow_dev"}, "msg": "unable to connect to database: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/var/run/postgresql/.s.PGSQL.5432\"?\n"}
```
